version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: textlint-rule-preset-ja-technical-writing
    versions:
    - 6.0.0
  - dependency-name: hexo-generator-search
    versions:
    - 2.4.2
  - dependency-name: highlight.js
    versions:
    - 10.7.1
    - 10.7.2
  - dependency-name: textlint
    versions:
    - 11.9.0
  - dependency-name: textlint-rule-preset-jtf-style
    versions:
    - 2.3.8
  - dependency-name: hexo-theme-next
    versions:
    - 8.2.1
